### PR TITLE
Trq/grackle3

### PR DESCRIPTION
**Pull request by trquinn**
This ports the cooling_grackle code to the 3.0 version of grackle.

### CODE REVIEW

**Comment by N-body-group-Reed** [comment]
Excellent.

**Comment by trquinn** [comment]
Seems to work (running AGORA cosmo sims), but needs to log the compile info.

**Comment by N-body-group-Reed** [comment]
fantastic news about ChaNGa.

When I substituted the "shielded" cloudy data for the "unshielded my
scripts stopped working.  So the first calibration
hasn't worked yet.  Running in SMP mode regularly now.

Beckett, my student, is making movies with the Tipsy files of the AGORA
runs.  Joel indicated that using that
data in his thesis was fine.

I continue to work on the code.pdf that you sent me.  A lot to learn ...
very fun

**Comment by MyGithubNotYours** [comment]
@trquinn The only way I can get Change to work is when I don't enable Grackle. I've tried various combinations of Grackle 2.1, 3.0, and 3.1 with Changa 3.3, 3.4, and master with no luck. What am I doing wrong? Here's the error when I try to use Grackle 3.0 with your branch (trq/grackle3) today:

```
Compiling Reductions.ci...
Compiling Orb3dLB_notopo.ci...
Compiling MultistepNodeLB_notopo.ci...
Compiling HierarchOrbLB.ci...
Compiling Orb3dLB.ci...
Compiling ParallelGravity.ci...
Compiling MultistepLB_notopo.ci...
Compiling MultistepLB.ci...
Compiling stiff.c...
Compiling moments.c...
Compiling runge.c...
Compiling romberg.c...
Compiling cosmo.c...
Compiling cha_commitid.c...
Compiling param.c...
Compiling cooling_grackle.c...
cooling_grackle.c: In function ‘CoolIntegrateEnergyCode’:
cooling_grackle.c:368:15: error: ‘grackle_field_data {aka struct <anonymous>}’ has no member named ‘grid_dx’; did you mean ‘grid_end’?
     my_fields.grid_dx = 0.0;
               ^~~~~~~
               grid_end
cooling_grackle.c: In function ‘CoolCodeEnergyToTemperature’:
cooling_grackle.c:580:15: error: ‘grackle_field_data {aka struct <anonymous>}’ has no member named ‘grid_dx’; did you mean ‘grid_end’?
     my_fields.grid_dx = 0.0;
               ^~~~~~~
               grid_end
cooling_grackle.c: In function ‘CoolEdotInstantCode’:
cooling_grackle.c:652:15: error: ‘grackle_field_data {aka struct <anonymous>}’ has no member named ‘grid_dx’; did you mean ‘grid_end’?
     my_fields.grid_dx = 0.0;
               ^~~~~~~
               grid_end
Fatal Error by charmc in directory /home/xxx/gits/changa-trq
```

**Comment by trquinn** [comment]
According to the grackle git repository, "grid_dx" got added to Grackle in Dec. 2016.  Be sure your grackle installation has this commit in it:
commit 4a8824fe96ffe4aabac4dbc6549be56a25cd1dec
Author: Andrew Emerick <emerick@astro.columbia.edu>
Date:   Tue Dec 13 17:15:50 2016 -0500

    H2 self shielding

I tested the code with the latest grackle master branch.  Going over the grackle revision history, it looks like you need at least grackle-3.1 in order to compile.

**Comment by N-body-group-Reed** [comment]
Not sure to whom I am responding.  I struggled with this Grackle issue for
months.  I am running ChaNGa 3.4 with Grackle 3.1.1 using
the Cloudy non-shielding NAME on Comet.  The helpdesk at XSEDE's Comet has
arranged to have ChaNGa that runs with Grackle as
a *module*.  My only suggestion is to get startup on Comet if you don't
have one, and then work with the wonderful Marty Kandes.

In several time crunches at the moment.

Best,

johnny powell

**Comment by MyGithubNotYours** [comment]
@trquinn 
Thanks much! However, now when I actually try to run the program, I get an error. The build process was successful. The tests ran successfully. Were you able to check if a simulation works or did you only test the building process? This is the error I'm getting:

```
Charm++: standalone mode (not using charmrun)
Charm++> Running in Multicore mode: 4 threads (PEs)
Converse/Charm++ Commit ID: v6.10.1
Warning> Randomization of virtual memory (ASLR) is turned on in the kernel, thread migration may not work! Run 'echo 0 > /proc/sys/kernel/randomize_va_space' as root to disable it, or try running with '+isomalloc_sync'.
CharmLB> Load balancer assumes all CPUs are same.
Charm++> Running on 1 hosts (1 sockets x 8 cores x 2 PUs = 16-way SMP)
Charm++> cpu topology info is gathered in 0.000 seconds.
[0] MultistepLB_notopo created
WARNING: iMaxRung parameter ignored. MaxRung is 30
WARNING: bKDK parameter ignored; KDK is always used.
WARNING: bStandard parameter ignored; Output is always standard.
Not Using CkLoop 0
ChaNGa version 3.4, commit v3.4-47-g16f0af3
Running on 4 processors/ 1 nodes with 32 TreePieces
yieldPeriod set to 5
Prefetching...ON
Number of chunks for remote tree walk set to 1
Chunk Randomization...ON
cache 1
cacheLineDepth 4
Verbosity level 1
Domain decomposition...SFC Peano-Hilbert
CkLoopLib is used in SMP with simple dynamic scheduling (converse-level notification)
Created 32 pieces of tree
Loading particles ... trying Tipsy ... took 0.024500 seconds.
N: 312500
Input file, Time:1.000000
Simulation to Time:68.081080
HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 139890127502656:
  #000: ../../../src/H5F.c line 579 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: ../../../src/H5Fint.c line 1100 in H5F_open(): unable to open file: time = Sat Mar 21 00:48:02 2020
, name = 'CloudyData_UVB=HM2012.h5', tent_flags = 0
    major: File accessibilty
    minor: Unable to open file
  #002: ../../../src/H5FD.c line 812 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #003: ../../../src/H5FDsec2.c line 348 in H5FD_sec2_open(): unable to open file: name = 'CloudyData_UVB=HM2012.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibilty
    minor: Unable to open file
HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 139890127502656:
  #000: ../../../src/H5A.c line 1693 in H5Aexists(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: ../../../src/H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
HDF5-DIAG: Error detected in HDF5 (1.10.0-patch1) thread 139890127502656:
  #000: ../../../src/H5Ddeprec.c line 189 in H5Dopen1(): not a location
    major: Invalid arguments to routine
    minor: Inappropriate type
  #001: ../../../src/H5Gloc.c line 253 in H5G_loc(): invalid object ID
    major: Invalid arguments to routine
    minor: Bad value
Can't open Cooling in CloudyData_UVB=HM2012.h5.
Error in initialize_cloudy_data.
Error in _initialize_chemistry_data.
Grackle Error in initialize_chemistry_data.
ChaNGa: cooling_grackle.c:127: clInitConstants: Assertion `0' failed.
Aborted (core dumped)
```


It looks like maybe it can't find "CloudyData_UVB=HM2012.h5" in the correct location. I checked and that file exists in the Grackle directory. Also, I'm trying to run this on my personal computer - will that cause any problems (8-core 3700X AMD Ryzen with 2060GTX GPU with 64 GB ram)?

**Comment by MyGithubNotYours** [comment]
@N-body-group-Reed 
Thanks for the suggestion. I'm reading the Comet website now :)

**Comment by trquinn** [comment]
The CloudyData file needs to be in the directory in which you are running ChaNGa.

**Comment by trquinn** [comment]
I've updated the [grackle cooling wki](https://github.com/N-BodyShop/changa/wiki/Grackle-Cooling) to make some of this more clear.  Let me know if anything more needs to be added.

**Comment by trquinn** [comment]
Regarding use on personal computers: yes, for small datasets this can run on small machines.

**Comment by N-body-group-Reed** [comment]
By Comet website I assume the XSEDE site.  The startup allocation procedure
is SPECTACULARLY quick and easy -- I made it way too difficult my first
time: just a simple paragraph or two and you're in quickly. You can
get supplements and extensions.  Prof. Quinn's admonishment about the
Cloudy data file is, of course, right.

Best of luck,

johnny

**Pull request merged**
