### PR TITLE
Add GPU_TREE_WALK flag to defines passed to all compilers.

### PR DESCRIPTION
**Pull request by trquinn**
This fixes issue #27.

### CODE REVIEW

**Comment by hainest** [comment]
I made a fix for[ th](https://github.com/hainest/changa/commit/32512f5de9e17faacc926bd53c695d2231bb1171)is over the weekend, but I didn't get a chance to test it (my crawl space flooded. Yay!). The only real difference is that you can also delete lines 58 and 59 since nvcc will inherit the `cuda_defines` through `cxx_flags`. I will try to test this soon.

**Comment by hainest** [comment]
I've tested my fix on Comet with no trouble. Is there a test case that can reproduce the original issue?

**Comment by trquinn** [comment]
I should have recorded the exact error, but pretty much any run with gpu_local_tree_walk would die in run_TP_GRAVITY_LOCAL at the cudaPeekAtLastError() because the grid_dim and block_dim for the kernel lauch at line 249 is garbage.  I discovered this on the dwf1.2048 benchmark (see /home/u14266/scratch/bench/dwf1.2048.param on comet).

**Comment by trquinn** [comment]
This pull request now matches Tim's fix.

**Comment by hainest** [comment]
The update looks good. I will try to re-run the benchmark to see if it crashes.

**Comment by hainest** [comment]
I was able to run the dwf1.2048.00384 example for 10 timesteps without issue using

```
#SBATCH --partition=gpu-shared
#SBATCH --gres=gpu:1
```

**Pull request merged**
